### PR TITLE
Return error when opening incorrect path

### PR DESCRIPTION
**Pull request by hwchen**
- when asking to open an existing tdb
- if the path does not exist
- tdb open will create an empty .sled at that path
- and silently ignore the check for version
- so, there's no error on open if you present the wrong path

This commit still allows the creation of a new empty db, but it returns an error on the taxonomy version check.

### CODE REVIEW

**Comment by hwchen** [comment]
It's not clear that sled has an option to return an error instead of creating a new db. https://docs.rs/sled/0.34.7/sled/struct.Config.html

One option is for us to check that the path exists before allowing sled to try.

**Comment by hwchen** [comment]
Now also checks that tdb path exists before allowing sled to open.

**Comment by vgel** [comment]
This is a good change, but it will break this nasty hack I was doing to skip taxonomy db initialization time in the RS integration test:

https://github.com/SecureDNA/dna_screening_tools/pull/246/files#diff-e6878de479676ce31d6cab26a602721be4065e92d26846b3e3392cfb356651e4R283-R284

Is there a good way to replace this, if we just want an empty taxonomy db?

**Comment by hwchen** [comment]
ah, I see :) . I had briefly wondered about this and then forgot.

A minimal taxonomy db generator now exists. We could even have a helper for generating an empty one, but that doesn't exist yet: https://github.com/SecureDNA/dna_screening_tools/tree/main/minimal_taxonomy_db . Will the current code work for you?

**Review by vgel — APPROVED** [review]

**Comment by hwchen** [comment]
Great, thanks :)

**Pull request merged**
